/**
 * Returns the line on the sheet where the header is located.
 * 
 * @param {Array} sheet 
 */
const _getHeaderLine = sheet => {
  const headerKeywords = ['cpf', 'nome'];
  let firstDataLine;
  const stringfy = value => '' + value;
  const found = sheet.some((line, lineNumber) => {
    firstDataLine = lineNumber + 1;
    const isHeader = line.length >= headerKeywords.length && headerKeywords.every((key, index) =>
      !!line[index] && stringfy(line[index]).toLowerCase().includes(key));
    return isHeader;
  });
  return found ? firstDataLine : undefined;
};

/**
 * Parses the spreadsheet object generated by the XLSX lib into the formated and clean object containing the extracted info. 
 
 * @param {Array} spreadsheet the spreadsheet object. 
 */
const parse = spreadsheet => {
  throw new Error('not implemented yet');  
};

module.exports = { parse, _getHeaderLine };